config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do 
    authenticated :user do 
      root 'users#current_user_home', as: :authenticated_root
    end

    unauthenticated do 
      root 'devise/registrations#new', as: :unauthenticated_root 
    end
  end

  resources :users do 
    member do 
      get :following, :followers 
    end

    resources :endorsements,  only: [:new, :create, :destroy]
    resources :comments,      only: [:create, :destroy]
  end

  resources :skills do
    resources :endorsements, only: [:new, :create, :destroy]
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :skills,        only: [:new, :create, :destroy]
  resources :employees,     only: [:new, :create, :destroy]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :commenter, class_name: "User"
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	has_many :endorsements
	
	belongs_to :user

	validates :work_email, presence: true
	validates :position,   presence: true
	validates :employer,   presence: true
end

app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
	belongs_to :endorser, class_name: "User"
	belongs_to :user
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"

	validates :follower_id, presence: true
	validates :followed_id, presence: true
end

app/models/skill.rb
class Skill < ActiveRecord::Base
	has_many :endorsements

	belongs_to :user

	validates :skill, presence: true
	validates :level, presence: true,
					  numericality: {greater_than_or_equal_to: 1,
					  				less_than_or_equal_to: 10}
end

app/models/user.rb
class User < ActiveRecord::Base


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    validates :name, presence: true
    validates :phone, presence: true

    has_many :skills
    has_many :employees

    # Following Relationships
    has_many :active_relationships, class_name: "Relationship",
                                   foreign_key: "follower_id",
                                     dependent: :destroy
    has_many :following, through: :active_relationships, source: :followed
    has_many :passive_relationships, class_name: "Relationship",
                                    foreign_key: "followed_id",
                                      dependent: :destroy
    has_many :followers, through: :passive_relationships, source: :follower

    # Person to Person Endorsements
    has_many :active_endorsements, class_name: "Endorsement",
                                  foreign_key: "endorser_id",
                                    dependent: :destroy
    has_many :endorsed, through: :active_endorsements, source: :endorser
    has_many :passive_endorsements, class_name: "Endorsement",
                                   foreign_key: "user_id",
                                     dependent: :destroy
    has_many :endorsements, through: :passive_endorsements, source: :user

    # Comments
    has_many :comments
    has_many :active_comments, class_name: "Comment",
                              foreign_key: "commented_id",
                                dependent: :destroy
    has_many :commenter, through: :active_comments, source: :commenter


  # Follows a user.
  def follow(other_user)
  	active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user
  def unfollow(other_user)
  	active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
  	following.include?(other_user)
  end

  # Endorses a User/Employee/Skill
  def endorse(current_user, other_user)
    active_endorsements.create(endorser_id: current_user.id, user_id: other_user.id)
  end

  # Unendorse a user.
  def unendorse(other_user)
    active_endorsements.find_by(user_id: other_user.id).destroy
  end

  # Returns true if the current user endorses the other user.
  def endorsing?(other_user)
    endorsed.include?(other_user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def after_sign_in_path_for(resource)
	@user=current_user
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@user = User.find(params[:user_id])
		@comment = @user.active_comments.create(comment_params)
		@comment.commenter_id = current_user.id
		@comment.user_id = @user.id
		if @comment.save
			redirect_to user_path(params[:user_id])
		else
			flasah.now[:danger] = "Comment did not save"
		end
	end			


	private

		def comment_params
			params.require(:comment).permit(:comment, :annonymous_flag)
		end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

	def create
		@employee = current_user.employees.build(employee_params)
		if @employee.save
			flash[:success] = "position saved"
			redirect_to authenticated_root_path(:id => current_user.id)
		else
			redirect_to new_employee_path
		end
	end



	private

		def employee_params
			params.require(:employee).permit(:work_email, :position, :employer)
		end

end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController

	def create
		@user = User.find(params[:user_id])
		current_user.endorse(current_user, @user)
		respond_to do |format|
			format.html {redirect_to @user}
			format.js
		end
	end

	def destroy
		@user =  User.find(params[:user_id])
		current_user.unendorse(@user)
		respond_to do |format|
			format.html {redirect_to @user}
			format.js
		end
	end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	before_action :user_signed_in?

  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end
  
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController

	def create
		@skill = current_user.skills.build(skill_params)
		if @skill.save
			flash[:success] = "skill saved"
			redirect_to authenticated_root_path(:id => current_user.id)
		else
			redirect_to new_skill_path
		end
	end



	private

		def skill_params
			params.require(:skill).permit(:skill, :level)
		end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :user_signed_in?, only: [:index]

	def index
		@users = User.all 
	end

	def show
		@user = User.find(params[:id])
	end

	def following
		@title = "Following"
		@user = User.find(params[:id])
		@users = @user.following.paginate(page: params[:page])
		render 'show_follow'
	end

	def followers
		@title = "Followers"
		@user = User.find(params[:id])
		@users= @user.followers.paginate(page: params[:page])
		render 'show_follow'
	end

	def current_user_home
		redirect_to current_user
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	#Returns the full title on a per-page basis.
	def full_title(page_title = '')
		base_title = "Zacs Linked In"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/employees/new.html.erb
<h1>New Job</h1>

<%= form_for(current_user.employees.build) do |f| %>

  <div class="field">
    <%= f.label :work_email %><br />
    <%= f.email_field :work_email %>
  </div>

  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>

  <div class="field">
    <%= f.label :employer %><br />
    <%= f.text_field :employer %>
  </div>

  <div class="actions">
    <%= f.submit "Add Skill" %>
  </div>

<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <% if user_signed_in? %>
  	  <%= link_to "Zacs Linked In", authenticated_root_path, id: "logo" %>
    <% else %>
      <%= link_to "Zacs Linked In", unauthenticated_root_path, id: "logo" %>
    <% end %>
  	<nav>
  		<ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to current_user.name, user_path(current_user) %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>

  			<li><%= link_to "Users", users_path %></li>
  			<li><%= link_to "Placeholder", '#' %></li>

  			<% if user_signed_in? %>
  				<li><%= link_to "Log Out", destroy_user_session_path, method: "delete" %></li>
  			<% end %>
  		</ul>
  	</nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
 	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
	</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
	</head>
	<body>
		<%= render 'layouts/header' %>

		<div class="container">
			<% flash.each do |message_type, message| %>
				<%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
			<% end %>
			<%= yield %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");
$("#followers").html('<%= @user.followers.count %>');

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");
$("#followers").html('<%= @user.followers.count %>');

app/views/shared/_comment_form.html.erb
<%= form_for Comment.new, :url => user_comments_path(user.id) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>

	<div class="field">
		<%= f.label :comment %>
		<%= f.text_area :comment %>
	</div>

	<div class="field">
		<%= f.label :annonymous_flag, "Annonymous" %>
		<%= f.check_box :annonymous_flag %>
	</div>

	<%= f.submit "Comment", class: "btn btn-primary" %>

<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/skills/new.html.erb
<h2>Add Skill</h2>

<%= form_for(current_user.skills.build) do |f| %>
	
  <div class="field">
    <%= f.label :skill %><br />
    <%= f.text_field :skill %>
  </div>

   <div class="field">
    <%= f.label :level %><br />
    <%= f.text_field :level %>
  </div>

   <div class="actions">
    <%= f.submit "Add Skill" %>
  </div>

<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user == @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
	<%= link_to user.name, user %>
</li>

app/views/users/index.html.erb
<% @users.each do |user| %>
	<%= link_to user.name, user_path(user.id) %><br>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
	<aside class="col-md-4">
		<section>
			<h1><%= @user.name %></h1>
			<%= @user.endorsements.count.to_s %> Endorsements
			<% unless current_user == @user %>
				<% if current_user.endorsing?(@user) %>
					<%= link_to "Unendorse User", user_endorsement_path(@user.id, current_user.id), :method => :delete %>
				<% else %>
					<%= link_to "Endorse User", user_endorsements_path(@user.id), :method => :post %><br>
				<% end %>
			<% end %>
			<p>
				<%= @user.phone %><br>
				<%= @user.email %><br>
			</p>
		</section>
		<section class="stats">
			<%= render 'shared/stats' %>
		</section>
		<section class="employees">
			<h1>Jobs</h1>
			<ul>
				<% @user.employees.each do |employee| %>
					<li><%= employee.position %></li>
					<ul>
						<li><%= employee.work_email %></li>
						<li><%= employee.employer %></li>
					</ul>
				<% end %>
			</ul>
			<% if current_user == @user %>
				<%= link_to "Add job", new_employee_path %>
			<% end %>
		</section>
		<section class="skills">
			<h2>Skills</h2>
			<ul>
				<% @user.skills.each do |skill| %>
					<li>
						<%= skill.skill + " " + skill.level.to_s %>
						<% unless current_user == @user %>
							<%= link_to "Endorse Skill", skill_endorsements_path(skill.id), :method => :post %>
						<% end %>
					</li>
				<% end %>
			</ul>
			<% if current_user == @user %>
				<%= link_to "Add Skill", new_skill_path %>
			<% end %>
		</section>
		<section class="Comments">
			<h2>Comments</h2>
			<% unless @user == current_user %>
				<h3>Post comment</h3>
				<%= render 'shared/comment_form', user: @user %>
			<% end %>
			<% if @user.comments.any? %>
				<% @user.comments.each do |comment| %>
					<p>
						Content: <%= comment.comment %><br>
						Author: <%= comment.commenter.name %>
					</p>
				<% end %>
			<% end %>
		</section>
	</aside>
	<div class="col-md-8">
		<%= render 'follow_form' if user_signed_in? %>
	</div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
	<aside class="col-md-4">
		<section class="user_info">
			<h1><%= @user.name %></h1>
			<span><%= link_to "view my profile", @user %></span>
		</section>
		<section class="stats">
			<%= render 'shared/stats' %>
		</section>
	</aside>
	<div class="col-md-8">
		<h3><%= @title %></h3>
		<% if @users.any? %>
			<ul class="users follow">
				<%= render @users %>
			</ul>
			<%= will_paginate %>
		<% end %>
	</div>
</div>